# Generated by Django 4.0.3 on 2023-11-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('food_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('food_carbs', models.DecimalField(decimal_places=1, max_digits=5)),
                ('food_proteins', models.DecimalField(decimal_places=1, max_digits=5)),
                ('food_fats', models.DecimalField(decimal_places=1, max_digits=5)),
                ('food_kcal', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('menu_date', models.DateTimeField()),
                ('menu_category', models.CharField(choices=[('1', '아침'), ('2', '점심'), ('3', '저녁'), ('4', '간식'), ('5', '야식')], max_length=20)),
                ('menu_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.food')),
                ('menu_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.photo')),
                ('menu_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
