# Generated by Django 4.0.3 on 2023-11-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('diet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('diet_start_day', models.DateTimeField()),
                ('diet_start_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('diet_target_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('diet_exercise', models.CharField(choices=[('1', '매우 비활동적'), ('2', '비활동적'), ('3', '보통'), ('4', '활동적'), ('5', '매우 활동적')], max_length=20)),
                ('diet_user_height', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'diet',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('weight_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight_current', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight_recorded', models.DateTimeField()),
                ('weight_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight',
            },
        ),
    ]
